version: "3.9"

services:
  web:
    container_name: web
    image: sharinobimbam/node-web-app
    ports:
      - "8123:80"
    environment:
      NODE_ENV: development
    volumes:
      - 'ftpdata:/usr/share/nginx/html'
      # - 'ftpdata:/mnt/ftpdata'
  ftp-server:
    container_name: ftp
    environment:
      - FTP_PASS=123
      - FTP_USER=user
    image: garethflowers/ftp-server
    ports:
      - '21:21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - 'ftpdata:/home/user'
volumes:
  ftpdata:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /tmp/ftpdata
      o: bind